"""
Markdown / HTML Digest Renderer
記事データを Markdown 形式のダイジェストとして出力し、HTML も生成する。
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import markdown
from jinja2 import Template


@dataclass
class DigestArticle:
    title: str
    source: str
    url: str
    summary: str
    category: str
    relevance_tag: str
    is_starred: bool = False


CATEGORY_LABELS = {
    "AI_RESEARCH": "AI Research",
    "AI_PRODUCT_SAAS": "AI Product / SaaS",
    "MACRO_STRUCTURE": "Macro & Structure",
    "JAPAN_SIGNAL": "Japan Signal",
    "AGRICULTURE": "Agriculture",
    "AI_DRIVEN_DEV": "AI Driven Development",
    "CAREER_HYBRID": "Career / Hybrid",
    "QIITA_TRENDING": "Qiita Trending",
    "NOTE_TRENDING": "note Trending",
    "X_BUZZ": "X Buzz",
    "AI_DRIVEN_DEV": "AI Driven Development",
    "CAREER_HYBRID": "Career / Hybrid",
}


def render_digest(
    articles_by_category: dict[str, list[DigestArticle]],
    generated_at: datetime,
    lookback_hours: int,
) -> str:
    lines: list[str] = []

    date_str = generated_at.strftime("%Y-%m-%d")
    time_str = generated_at.strftime("%H:%M JST")
    lines.append(f"# Daily Digest - {date_str}")
    lines.append("")
    lines.append(f"**生成時刻:** {time_str}")
    lines.append(f"**対象範囲:** 過去 {lookback_hours} 時間")
    total = sum(len(arts) for arts in articles_by_category.values())
    lines.append(f"**記事数:** {total} 件")
    lines.append("")
    lines.append("---")
    lines.append("")

    all_cat_keys = list(CATEGORY_LABELS.keys()) + [
        k for k in articles_by_category if k not in CATEGORY_LABELS
    ]

    for cat_key in all_cat_keys:
        articles = articles_by_category.get(cat_key, [])
        if not articles:
            continue
        cat_label = CATEGORY_LABELS.get(cat_key, cat_key)

        lines.append(f"## {cat_label}")
        lines.append("")

        for i, art in enumerate(articles, 1):
            star = " ⭐" if art.is_starred else ""
            lines.append(f"### {i}. {art.title}{star}")
            lines.append(f"**出典:** {art.source} | [記事リンク]({art.url})")
            lines.append("")
            lines.append(f"> {art.summary}")
            lines.append("")
            if art.relevance_tag:
                lines.append(f"**転用示唆:** {art.relevance_tag}")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(f"*Generated by content-hub at {time_str}*")
    lines.append("")

    return "\n".join(lines)


def render_html(md_content: str, date_str: str) -> str:
    html_body = markdown.markdown(md_content, extensions=["extra", "sane_lists"])

    template = Template(DEFAULT_TEMPLATE)
    return template.render(
        title=f"Daily Digest - {date_str}",
        content=html_body,
        date=date_str,
    )


def save_digest(output_dir: Path, md_content: str, date_str: str) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    dated_md = output_dir / f"{date_str}.md"
    latest_md = output_dir / "latest.md"
    dated_html = output_dir / f"{date_str}.html"
    index_html = output_dir / "index.html"

    dated_md.write_text(md_content, encoding="utf-8")
    latest_md.write_text(md_content, encoding="utf-8")

    html = render_html(md_content, date_str)
    dated_html.write_text(html, encoding="utf-8")
    index_html.write_text(html, encoding="utf-8")

    return {
        "dated_md": dated_md,
        "latest_md": latest_md,
        "dated_html": dated_html,
        "index_html": index_html,
    }


DEFAULT_TEMPLATE = """<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <style>
    :root { --bg: #0d1117; --fg: #e6edf3; --muted: #8b949e; --accent: #58a6ff; --border: #30363d; --card: #161b22; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
           background: var(--bg); color: var(--fg); line-height: 1.7; padding: 2rem; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 1.8rem; margin-bottom: 0.5rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
    h2 { font-size: 1.3rem; color: var(--accent); margin-top: 2rem; margin-bottom: 0.8rem; }
    h3 { font-size: 1.05rem; margin-top: 1.2rem; }
    p { margin: 0.5rem 0; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    hr { border: none; border-top: 1px solid var(--border); margin: 1.5rem 0; }
    blockquote { border-left: 3px solid var(--accent); padding: 0.5rem 1rem; margin: 0.8rem 0;
                 background: var(--card); border-radius: 0 6px 6px 0; color: var(--muted); }
    strong { color: var(--fg); }
    code { background: var(--card); padding: 0.15em 0.4em; border-radius: 4px; font-size: 0.9em; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.85rem; }
  </style>
</head>
<body>
  {{ content }}
  <div class="footer">
    <p>Powered by <a href="#">content-hub</a> &middot; GitHub Actions + Pages</p>
  </div>
</body>
</html>"""
